## Benchmark-specific linter rules

env:
  node: true
  es6: true

rules:
  prefer-arrow-callback: error

overrides:
  - files:
      - http/*.js
      - path/*.js
    rules:
      comma-dangle: [error, {
        arrays: always-multiline,
        exports: always-multiline,
        functions: only-multiline,
        imports: always-multiline,
        objects: only-multiline,
      }]
