name: Test UBSan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/ubsan-asan.yml'
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/ubsan-asan.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-ubsan:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    env:
      CC: gcc
      CXX: g++
      LINK: g++
      CONFIG_FLAGS: --enable-ubsan
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Store suppressions path
        run: |
          echo "UBSAN_OPTIONS=suppressions=$GITHUB_WORKSPACE/suppressions.supp" >> $GITHUB_ENV
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions -t 300 --measure-flakiness 9"
